export const PATH = {
  ROOT: '/',
  CHANNEL: '/channel',
  CHANNEL_CREATE: '/channel/new',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  MYPAGE: '/mypage',
  MYPAGE_PROFILE_UPDATE: '/mypage/profile-update',
  MYPAGE_FOLLOW: '/mypage/follow',
  MYPGE_POST_LIST: '/mypage/post-list',
  MYPGE_LIKE_LIST: '/mypage/like-list',
  MYPGE_COMMNET_LIST: '/mypage/comment-list',
  MYPGE_PASSWORD_UPDATE: '/mypage/password-update',
  MYPGE_RECEIVED_POST_LIST: '/mypage/received-post-list',
  POST_CREATE: '/post/new',
  POST: '/post',
  COMMENT: '/comment',
  MESSAGELIST: '/messageList',
  MESSAGE: '/message',
  USER: 'user'
};
